DROP TABLE IF EXISTS NACE_ACTIVITIES;  

CREATE TABLE NACE_ACTIVITIES (  
ACT_ORDER VARCHAR(50) PRIMARY KEY,  
ACT_LEVEL VARCHAR(50), 
ACT_CODE VARCHAR(50), 
ACT_PARENT VARCHAR(50), 
DESCRIPTION VARCHAR(50), 
ITEM_INCLUDE VARCHAR(50), 
ITEM_ALSO_INCLUDE VARCHAR(50),
RULINGS VARCHAR(50),
ITEM_EXCLUDE VARCHAR(50),
REFERENCE VARCHAR(50)  
); 


INSERT INTO NACE_ACTIVITIES VALUES (11, 'DELHI', 110001,null,null,null,null,null,null,null);   